from .meta_comb_node import (
    NODE_CLASS_MAPPINGS as META_COMB_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as META_COMB_DISPLAY_MAPPINGS,
)
from .load_image_node import (
    NODE_CLASS_MAPPINGS as LOAD_IMAGE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LOAD_IMAGE_DISPLAY_MAPPINGS,
)

# Combine all node mappings
NODE_CLASS_MAPPINGS = {
    **META_COMB_MAPPINGS,
    **LOAD_IMAGE_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **META_COMB_DISPLAY_MAPPINGS,
    **LOAD_IMAGE_DISPLAY_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
